### ISSUE TITLE
From perception to decision: A data-driven approach to end-to-end motion planning for autonomous ground robots

### ISSUE THREAD

**Issue by luo-pan** [ethz-asl/ai_for_robotics#20]
Respected Mr Pfeiffer, I have been honored to read your article named by "From perception to decision: A data-driven approach to end-to-end motion planning for autonomous ground robots" in the ICRA this year. I am
very impressed with the  neural network-based motion planner you present in the article. Moreover, I am also interested in how to implement the model in my robot. To be honest, I have learned TensorFlow framework recently, but to complete a model like that  in short order is really difficult to me, a  beginner. So would you like to share the model and the programs to more learners like me? Thank you very much!

**Comment by pfmark** [comment]
Dear @luo-pan 

Thank's for reaching out regarding the paper. I'm happy that you liked it. The whole software stack will not be open sourced right now, sorry. However, I'm happy to help with sepcific questions. 

Let me know if I can help with something. Ideally, you can contact me at pfmark@ethz.ch . 

Best,
Mark

**Comment by luo-pan** [comment]
Thank you, professor Mark! I will try to program in the TensorFlow based on the information provided in your paper. And I am sorry that I will trouble you in the future with sepcific questions.

**Comment by ffurrer** [comment]
closing this, as this will be handled via email and doesn't really belong to this repo.
